### ISSUE TITLE
What is expected way of installing magento? Errors after using composer create-project

### ISSUE THREAD

**Issue by Zankierka** [nithincninan/magento2-docker#1]
Hi,

I think I might get something wrong so I would really appreciate if you can help me here.
After deployment of magento 2.3.1 using composer create-project and so on everything was fine.

Installer was running - but after successful installation it crashes like so:
`Fatal error: Uncaught RuntimeException: The path "/var/www/magento23/generated/code/Magento/Framework/App/Config/InitialConfigSource/Proxy.php.6" cannot be renamed into "/var/www/magento23/generated/code/Magento/Framework/App/Config/InitialConfigSource/Proxy.php" Warning!rename(/var/www/magento23/generated/code/Magento/Framework/App/Config/InitialConfigSource/Proxy.php.6,/var/www/magento23/generated/code/Magento/Framework/App/Config/InitialConfigSource/Proxy.php): No such file or directory Class Magento\Framework\App\Config\InitialConfigSource\Proxy generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only. in /var/www/magento23/vendor/magento/framework/Code/Generator.php:135 Stack tra in /var/www/magento23/vendor/magento/framework/Code/Generator.php on line 135`

![image](https://user-images.githubusercontent.com/18290902/60883370-59d63180-a24a-11e9-81f8-53a4d87e849c.png)

Straight after installation error was present for different file.
It seems like php container does list such file - and I can't remove it.

`bin/magento setup:di:compile` - also does not work.
Did anybody get similar problem?

**Comment by nithincninan** [comment]
@Zankierka Sorry for the late message.. if you fixed this i can close this ticket or else i can help here

**Comment by nithincninan** [comment]
closing this ticket
