### ISSUE TITLE
After docker build nginx & xdebug Issue

### ISSUE THREAD

**Issue by alaminmishu** [nithincninan/magento2-docker#27]
After step 4:
nginx container not running
docker exec -it 5d9e00e77923 bash -l 
Error response from daemon: Container 5d9e00e779239b31d0d3d6940993fe54749e09c4d66729420575bc6d5c324fce is not running

My machine (Ubuntu 20.04 LTS)

Getting this from php container:
in step 5 (4)
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(

**Comment by nithincninan** [comment]
@alaminmishu 

1. nginx container not running

>> can you check 'nginx.conf.sample' file is present in magento root (magento24) folder.

ie, run composer install from magento root (magento24) folder. this file will generate.


2.Xdebug:

>>> xdebug is enabled in php container..
 if you disable the xdebug settings from php.ini - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini. it will be removed, and once disable restart the php container.- This is for debugging.

Thanks!
Nithin Ninan

**Comment by nithincninan** [comment]
please let me know if you face this issue

**Comment by nithincninan** [comment]
closing this thread!
