### ISSUE TITLE
nginx: [emerg] open() "/var/www/nginx.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:19

### ISSUE THREAD

**Issue by boris1988** [nithincninan/magento2-docker#28]
Hi 
In your default.conf I can find line with  include /var/www/nginx.conf;
but we did not map any files to /var/www/nginx.conf;
Thanks

**Comment by boris1988** [comment]
I added - ./docker/nginx/m2-config/nginx.conf:/var/www/nginx.conf to the volumes

**Comment by nithincninan** [comment]
Sure will add that. Thanks for pointing that out. - @boris1988
